// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20251027172847_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            Name = "China"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Philippines",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thailand",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "China",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Palestinian Territory",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "China",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
